### ISSUE TITLE
Uploaded image file getting corrupted after parse.

### ISSUE THREAD

**Issue by SatejMore** [francismeynard/lambda-multipart-parser#2]
Hello,

I am uploading jpeg image file, but after performing parse operation using this library the image data is getting converted into buffer having '7 bit' encoding data.

How can I get this buffer data as base64 data after performing parsing operation? 
If I use the same 7 bit encoded buffer data the image is getting corrupted. I am using node.js as a coding language?

Any suggestion regarding this would be great help. 

Thanks & Regards,
Satej

**Comment by pinodex** [comment]
Have you got the `Use Lambda Proxy integration` enabled in your API Gateway?

**Comment by francismeynard** [comment]
Hi there, have you enabled the Lambda proxy integration by any change in your api method?

From docs/readme -
"Important: Please make sure to enable the "Use Lambda Proxy integration" in API Gateway method Integration request."

**Comment by francismeynard** [comment]
Closing this issue now. Refer to docs with regards to enabling the "Use Lambda Proxy integration" in API Gateway. Thank

**Comment by tanoabeleyra** [comment]
I struggled with this too. The problem was that `multipart/form-data` needs to be configured as "Binary Media Type" in the API Gateway.
<img width="217" alt="image" src="https://user-images.githubusercontent.com/6851095/116643521-a0c57780-a947-11eb-85ef-cb1577e7e651.png">
